### ISSUE TITLE
Does job_templates method in app.py need to be a class method?

### ISSUE THREAD

**Issue by swainn** [CI-WATER/tethys#103]
Although it may be more correct to implement this method as a class method, is it required for the implementation? It could be adding unnecessary complication for app developers.

**Comment by sdc50** [comment]
The app developer either needs to include the @classmethod decorator or
they would need to instantiate the app class in their controller. I'm not
sure which method is less confusing.

**Comment by swainn** [comment]
Do they call that method? I thought they were calling something else in the controller. Could they call a class method you define in the parent class that instantiatea itself and then calls an instance method on that instance?

**Comment by sdc50** [comment]
I did as you suggested and had the get_job_manager method in the app_base class instantiate the class to call the get_templates method, so it no longer needs to be a classmethod.
