### ISSUE TITLE
Object Interfaces for Tethys Gizmos

### ISSUE THREAD

**Issue by swainn** [CI-WATER/tethys#28]
* Options for Tethys Gizmos specified with objects, rather than dictionaries.
* Create classes for each Tethys Gizmo options object
* Will allow for cleaner abstraction from the gizmo
* Continue supporting dictionary format for backwards compatibility

**Special Cases**

* Create special subclasses of the Highcharts objects that provide reasonable defaults for different plots (e.g. HighChartsLinePlot, HighChartsScatterPlot, etc.)

**Comment by ezrajrice** [comment]
Completed.
