### ISSUE TITLE
Formalize Workspaces for Apps

### ISSUE THREAD

**Issue by swainn** [CI-WATER/tethys#30]
Create a mechanism for working with files in apps.

* Provide a workspace directory for apps to work in
* Create an SDK method either for obtaining the path to that workspace another means of stashing stuff there.

**Comment by swainn** [comment]
Consider using decorators as a means of automatically setting the current working directory to the to some workspace directory for a controller. See this article about decorators:

http://www.google.com/url?q=http%3A%2F%2Fchimera.labs.oreilly.com%2Fbooks%2F1230000000393%2Fch09.html%23_defining_a_decorator_that_takes_arguments&sa=D&sntz=1&usg=AFQjCNEt2Jb-phc0_dLx5eMC0_Y4mnyZNg

**Comment by swainn** [comment]
Scott says: workspace directories should be included in the app project as part of the scaffold.

**Comment by swainn** [comment]
Consider copying contents of workspace into a centralized location and symbolically linking back to the app project directory for production cases. This would allow administrators the ability to locate a centralized workspace directory on a mounted drive and manage the storage for apps better.

**Comment by sdc50** [comment]
Keep workspace local to app (inside app directory)
Add workspace folder as part of the scaffold
Prepend user workspaces with "user" and app workspaces with "app" or nest in directories named user_workspaces and app_workspaces.

Methods

WorkspaceObject
  -path
  -files(absolute)
  -directories(absolute)
  -clear(exclude=[])

workspace_instance = get_user_workspace(user)
workspace_instance = get_app_workspace()

**Comment by swainn** [comment]
Done.
