### ISSUE TITLE
Add attributes option to all gizmos

### ISSUE THREAD

**Issue by swainn** [CI-WATER/tethys#45]
Add an "attributes" option to all gizmos. The value of this option will be a string representing additional HTML attributes to add to the element being generated:

attributes='onclick=runme(); class=a-class'

would result in <element onclick="runme()"; class="a-class"></element>

**Comment by ezrajrice** [comment]
Typical HTML element:

<div id="bob" class="red thick" onclick="runme();"></div>

With Gizmos:

{% gizmo text_input text_input_options %}

text_input_options = TextInputOption(... attributes="onclick=runme();" ...)

(1) Add "attributes" parameter to TethysGizmoOptionsBase
(2) Modify HTML templates to handle "attributes" parameter

This will involve adding the following to the appropriate HTML element: 

{% if attributes %}{{ attributes }}{% endif %}

Excluding: message_box.html, table_view.html, button_group.html, fetchclimate.html, google_map.html, google_map_view.html
