### ISSUE TITLE
Subclass HighCharts Gizmo for specific Plot types

### ISSUE THREAD

**Issue by swainn** [CI-WATER/tethys#47]
Create special subclasses of the Highcharts objects that provide reasonable defaults for different plots (e.g. HighChartsLinePlot, HighChartsScatterPlot, etc.)
* Line Plot
* Scatter Plot
* Spiderweb/Polar Plot
* Pie Plot
* Bar/Column Plot

See the Highcharts Demo Page for examples: http://www.highcharts.com/demo

**Comment by swainn** [comment]
API Reference: http://api.highcharts.com/highcharts

**Comment by ezrajrice** [comment]
Line Plot is completed. Now working on Scatter Plot.

**Comment by ezrajrice** [comment]
Scatter Plot, Polar Plot, and Pie Plot completed.
