### ISSUE TITLE
Fix Issues with Mac Installation Instructions

### ISSUE THREAD

**Issue by swainn** [CI-WATER/tethys#63]
Fix Documentation for Mac installation instructions to recommend using boot2docker version 1.3.3.
Also, provide the recipe for troubleshooting the SSL issues:

» brew switch openssl 1.0.1j
Error: openssl does not have a version "1.0.1j" in the Cellar.
Versions available: 1.0.2a-1
» brew unlink openssl
Unlinking /usr/local/Cellar/openssl/1.0.2a-1... 1543 symlinks removed
» brew install https://raw.githubusercontent.com/Homebrew/homebrew/62fc2a1a65e83ba9dbb30b2e0a2b7355831c714b/Library/Formula/openssl.rb
...
brew link --force openssl

**Comment by swainn** [comment]
Here are some helpful links if this issue is encountered again:

https://github.com/docker/docker-py/issues/465
https://github.com/docker/compose/issues/890
https://github.com/Homebrew/homebrew/issues/31851
http://stackoverflow.com/questions/25372911/python-pip-error-on-osx
https://github.com/Homebrew/homebrew/issues/38226

**Comment by dcousineau** [comment]
@swainn I may love you, if this fixes my mildly-related gcloud issues...

**Comment by dcousineau** [comment]
Yeah this isn't doing it for me, Homebrew still forces an updated openssl regardless of what openssl you have installed previously and pinned. Switching to the older openssl post install causes `import ssl` to fail.
