### ISSUE TITLE
 .tethyscluster Directory Creation causes Error in Production

### ISSUE THREAD

**Issue by swainn** [CI-WATER/tethys#7]
**Description**

* Error at Runtime with Production Installation caused by inability to create .tethyscluster directory
* This works in development mode, but causes permissions error in production installation: 
    * .tethyscluster directory created in home directory of the current user (/var/www/tethys/.tethyscluster?)
    * In production user running Tethys is the Apache user
    * Home directory of Tethys user is the /var/www directory which is owned by the root user
    * Hence, Tethys doesn't have the ability to create it automatically

**Suggestions**

* Option 1: Create a "tethys" user that owns all Tethys source and belongs to the Apache group during production installation to allow the appropriate permissions.
* Option 2: Mitigate through docs by including instructions to manually create the .tethyscluster directory during production installation.
* Option 3: Move .tethyscluster directory to the tethys src directory.
* Others?

**Comment by sdc50** [comment]
I need to look into what rights the Apache user has and see if it would be possible to run Apache as a different user. 

Look at the way CKAN does it.
