### ISSUE TITLE
HighCharts Plot Options Objects Don't Allow Overriding as They Should

### ISSUE THREAD

**Issue by swainn** [CI-WATER/tethys#98]
When trying to override the x_axis or y_axis options of HighChartsTimeSeries I encounter the following error: 

TypeError at /apps/dam-break/hydrograph/
__init__() got multiple values for keyword argument 'x_axis'

Here is the configuration the produces the error:

flood_hydrograph_plot = HighChartsTimeSeries(
            title='Flood Hydrograph',
            spline=True,
            y_axis_title='Flow',
            y_axis_units='cms',
            series=[
               {
                   'name': 'Flood Hydrograph',
                   'color': '#0066ff',
                   'data': hydrograph
               },
            ],
            x_axis={'min': 0}
    )

Options objects should allow for overriding any option from the HighCharts API using the kwargs. Please fix all HighCharts objects to allow this behavior.

**Comment by sdc50** [comment]
This is a false alarm. The reason the object was not being overriden is because the property to override is called xAxis not x_axis.
